services:
  n8n-vtex: 
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: "America/Sao_Paulo"
    restart: unless-stopped
    container_name: n8n-vtex
    networks:
      - n8n-vtex

networks:
  n8n-vtex:
    driver: bridge